# Generated by Django 2.2.14 on 2020-08-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='role',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(),
        ),
    ]
