# Generated by Django 2.2.14 on 2020-08-30 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200831_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='role',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
