# Generated by Django 2.2.14 on 2020-08-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200831_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='role',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
