# Generated by Django 2.2.14 on 2020-08-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200830_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.RemoveField(
            model_name='item',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='role',
        ),
        migrations.RemoveField(
            model_name='item',
            name='startDate',
        ),
    ]
