# Generated by Django 2.2.14 on 2020-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200830_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='endDate',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='role',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='startDate',
            field=models.DateField(default=''),
        ),
    ]
