# Generated by Django 2.2.14 on 2020-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200830_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='startDate',
            field=models.DateField(),
        ),
    ]
