# Generated by Django 2.2.14 on 2020-08-30 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200830_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
