# Generated by Django 2.2.14 on 2020-08-30 17:04

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200830_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='endDate',
            field=partial_date.fields.PartialDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='startDate',
            field=partial_date.fields.PartialDateField(blank=True, null=True),
        ),
    ]
